<?php

// Establishes accepted URL paths for the bookmarklets
function bookmarklet_processor_menu() {
  $items['flag/favorite/%/%'] = array(
    'page callback' => 'bookmarklet_processor_flag_favorite_process',
    'access callback' => TRUE,
    'page arguments' => array(2,7),
  );
  $items['flag/mark-for-review'] = array(
    'page callback' => 'bookmarklet_processor_flag_mark_for_review_process',
    'access callback' => TRUE,
  );
  $items['user/recreate-code'] = array(
  	'page callback' => 'bookmarklet_processor_user_recreate_code',
  	'access callback' => 'change own username',
  );
  return $items;
}

// Generate unique bookmarklet code
function bookmarklet_processor_generate_bookmarklet_code() {
	global $user;
	$code = sha1(uniqid());
	// Must be unique
	// The likelihood of this happending is absurdly low, but it needs to be done.
	$user_object = user_load($user->uid);
	$user_object->field_bookmarklet_code['und'][0]['value'] = bookmarklet_processor_generate_bookmarklet_code();
	user_save($user_object);
	return $code;
}

// Sets up the user's unique bookmarklet code
function bookmarklet_processor_user_insert(&$edit, $account, $category) {
	$code = bookmarklet_processor_generate_bookmarklet_code();
	dsm("Your bookmarklet code has been generated, and the bookmarklet is below.<br />
		$code");
}

// Allows user to recreate their unique code, in the event of abuse
function bookmarklet_processor_user_recreate_code() {
	$new_code = bookmarklet_processor_generate_bookmarklet_code();
	dsm("Your new bookmarklet code has been generated, and the new bookmarklet is below.<br />
		$new_code");
}

// Request to add a module to a user's favorites
function bookmarklet_processor_flag_favorite_process($user_code = null, $project_name = null) {
  bookmarklet_processor_module_node_exists($project_name);
  return "The module <strong>$project_name</strong> has been added to your favorites.";
}

// Request to add a module to a user's review list
function bookmarklet_processor_flag_mark_for_review_process($user_code = null, $project_name = null) {
  bookmarklet_processor_module_node_exists($project_name);
  return "The module <strong>$project_name</strong> has been added to your review list.";
}

// Check for the module node and create it if it doesn't exist
function bookmarklet_processor_module_node_exists($project_name) {
	$query = "SELECT * FROM `field_data_field_drupal_org_url_token` WHERE `field_drupal_org_url_token_value` = '$project_name'";
	$result = db_select('field_data_field_drupal_org_url_token')
     				->fields('field_data_field_drupal_org_url_token')
     				->condition('field_drupal_org_url_token_value',$project_name,'=')
     				->execute()
     				->fetchAssoc();
  if (empty($result['field_drupal_org_url_token_value'])) {
  	bookmarklet_processor_create_module_from_project_name($project_name);
  }
}

function bookmarklet_processor_create_module_from_project_name($project_name) {
	

  $url = 'http://www.drupal.org/project/' . $project_name;
  // Overriding for development reasons
  //$url = 'http://localhost:8082/views.html';
  $ch = curl_init(); 
  curl_setopt($ch, CURLOPT_URL, $url); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 

  // These options are required to prevent drupal.org anti-scraping security methods
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION,true);
  curl_setopt($ch, CURLOPT_USERAGENT,'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13');  
  curl_setopt($ch, CURLOPT_REFERER,'https://www.google.com/search?q=views&aq=f&sourceid=firefox&ie=UTF-8');
  curl_setopt($ch, CURLOPT_FRESH_CONNECT,true);

  // Execute the curl command
  $data = curl_exec($ch);

  curl_close($ch);

  // Acquire the module title
  $pattern = '/>(.*?)<\/h1>/';
  preg_match_all($pattern, $data, $matches);
  $module_title = $matches[1][0];
  $matches = array();

  // Acquire the module number of times installed
  $pattern = '/<li>Reported installs: <strong>(.*?)<\/strong>/';
  preg_match_all($pattern, $data, $matches);
  $module_times_installed = $matches[1][0];
  $matches = array();

  // Determine if the module is compatible with various versions, and record known versions
  $major_versions = array(6,7,8);
  $module_versions = array();
  $module_compatibilities = array();
  foreach ($major_versions as $major_version) {
    $pattern = '/<a href="\/node\/\d+">(' . $major_version . '\.x-\d\.[\d|x]+[-a-z]*?)<\/a>/';
    preg_match_all($pattern, $data, $matches);
    if (count($matches[1]) > 0) {
      foreach ($matches[1] as $match) {
      	dsm($match);
        array_push($module_versions, $match);
        array_push($module_compatibilities, $major_version);
      }
    }
  }
  $matches = array();
  
  // Generate the new module using the acquired information
  $node = new stdClass();
  $node->type = 'module';
  node_object_prepare($node);
  $node->title = $module_title;
  $node->language = LANGUAGE_NONE;
  $node->field_drupal_org_url_token['und'][0]['value'] = $project_name;
  $node->field_compatibility['und'] = array();
  $node->field_install_times['und'][0]['value'] = $module_times_installed;
  foreach ($module_compatibilities as $module_compatibility) {
    $terms = taxonomy_get_term_by_name($module_compatibility);
    foreach ($terms as $term) {
      array_push($node->field_compatibility['und'], array('tid' => $term->tid));
    }
  }
  $node->field_versions['und'][0]['value'] = '';
  foreach ($module_versions as $module_version) {
    $node->field_versions['und'][0]['value'] .= "$module_version,";
  }
  node_save($node);
}
